# 我没有写更详细的说明, 但你应该用不到这些配置
config-version: 0

matcher:
  # 原消息检查, 用轻量的方法检查原消息是不是我们需要的, 防止正则处理其他消息而浪费性能
  original-message-inspect:
    # 消息长度是否小于此值
    length: 320
    # 消息是否以此字符串开头
    prefix: '{"extra":[{"hov'

  # 用于匹配原消息中的物品名, 程序将获取第一个捕获组的结果
  regex: '\{"color":"#31b0e8","text":"([a-z0-9_]+)§f\."\}'
  # 将以上正则匹配到的消息替换为以下内容. 可用变量:
  #   __ItemName__        = 正则匹配到的实体/物品/方块名
  #   __TranslatedName__  = 转换后用于翻译的名称 "entity.minecraft.allay"
  replace-to: '{"color":"#31b0e8","extra":[{"translate":"__TranslatedName__"},{"text":" §8__ItemName__"}],"text":""}'

name:
  # %UseTranslatedNames_name_<生物/物品/方块 名>% -> [entity|item|block].minecraft.[name]
  # [占位符] -> [是否存在于 entity] -> [是否存在于 item] -> [block]
  # 此列表版本: 1.19.2

  # 所有实体
  list-entity_minecraft:
    - allay
    - area_effect_cloud
    - armor_stand
    - arrow
    - axolotl
    - bat
    - bee
    - blaze
    - boat
    - cat
    - cave_spider
    - chest_boat
    - chest_minecart
    - chicken
    - cod
    - command_block_minecart
    - cow
    - creeper
    - dolphin
    - donkey
    - dragon_fireball
    - drowned
    - egg
    - elder_guardian
    - end_crystal
    - ender_dragon
    - ender_pearl
    - enderman
    - endermite
    - evoker
    - evoker_fangs
    - experience_bottle
    - experience_orb
    - eye_of_ender
    - falling_block
    - fireball
    - firework_rocket
    - fishing_bobber
    - fox
    - frog
    - furnace_minecart
    - ghast
    - giant
    - glow_item_frame
    - glow_squid
    - goat
    - guardian
    - hoglin
    - hopper_minecart
    - horse
    - husk
    - illusioner
    - iron_golem
    - item
    - item_frame
    - killer_bunny
    - leash_knot
    - lightning_bolt
    - llama
    - llama_spit
    - magma_cube
    - marker
    - minecart
    - mooshroom
    - mule
    - ocelot
    - painting
    - panda
    - parrot
    - phantom
    - pig
    - piglin
    - piglin_brute
    - pillager
    - player
    - polar_bear
    - potion
    - pufferfish
    - rabbit
    - ravager
    - salmon
    - sheep
    - shulker
    - shulker_bullet
    - silverfish
    - skeleton
    - skeleton_horse
    - slime
    - small_fireball
    - snow_golem
    - snowball
    - spawner_minecart
    - spectral_arrow
    - spider
    - squid
    - stray
    - strider
    - tadpole
    - tnt
    - tnt_minecart
    - trader_llama
    - trident
    - tropical_fish
    - turtle
    - vex
    - villager
    - vindicator
    - wandering_trader
    - warden
    - witch
    - wither
    - wither_skeleton
    - wither_skull
    - wolf
    - zoglin
    - zombie
    - zombie_horse
    - zombie_villager
    - zombified_piglin

  # 所有物品
  list-item_minecraft:
    - acacia_boat
    - acacia_chest_boat
    - allay_spawn_egg
    - amethyst_shard
    - apple
    - armor_stand
    - arrow
    - axolotl_bucket
    - axolotl_spawn_egg
    - baked_potato
    - bat_spawn_egg
    - bee_spawn_egg
    - beef
    - beetroot
    - beetroot_seeds
    - beetroot_soup
    - birch_boat
    - birch_chest_boat
    - black_dye
    - blaze_powder
    - blaze_rod
    - blaze_spawn_egg
    - blue_dye
    - bone
    - bone_meal
    - book
    - bow
    - bowl
    - bread
    - brewing_stand
    - brick
    - brown_dye
    - bucket
    - bundle
    - carrot
    - carrot_on_a_stick
    - cat_spawn_egg
    - cauldron
    - cave_spider_spawn_egg
    - chainmail_boots
    - chainmail_chestplate
    - chainmail_helmet
    - chainmail_leggings
    - charcoal
    - chest_minecart
    - chicken
    - chicken_spawn_egg
    - chorus_fruit
    - clay_ball
    - clock
    - coal
    - cocoa_beans
    - cod
    - cod_bucket
    - cod_spawn_egg
    - command_block_minecart
    - compass
    - cooked_beef
    - cooked_chicken
    - cooked_cod
    - cooked_mutton
    - cooked_porkchop
    - cooked_rabbit
    - cooked_salmon
    - cookie
    - copper_ingot
    - cow_spawn_egg
    - creeper_banner_pattern
    - creeper_spawn_egg
    - crossbow
    - cyan_dye
    - dark_oak_boat
    - dark_oak_chest_boat
    - debug_stick
    - diamond
    - diamond_axe
    - diamond_boots
    - diamond_chestplate
    - diamond_helmet
    - diamond_hoe
    - diamond_horse_armor
    - diamond_leggings
    - diamond_pickaxe
    - diamond_shovel
    - diamond_sword
    - disc_fragment_5
    - dolphin_spawn_egg
    - donkey_spawn_egg
    - dragon_breath
    - dried_kelp
    - drowned_spawn_egg
    - echo_shard
    - egg
    - elder_guardian_spawn_egg
    - elytra
    - emerald
    - enchanted_book
    - enchanted_golden_apple
    - end_crystal
    - ender_eye
    - ender_pearl
    - enderman_spawn_egg
    - endermite_spawn_egg
    - evoker_spawn_egg
    - experience_bottle
    - feather
    - fermented_spider_eye
    - filled_map
    - fire_charge
    - firework_rocket
    - firework_star
    - fishing_rod
    - flint
    - flint_and_steel
    - flower_banner_pattern
    - flower_pot
    - fox_spawn_egg
    - frog_spawn_egg
    - furnace_minecart
    - ghast_spawn_egg
    - ghast_tear
    - glass_bottle
    - glistering_melon_slice
    - globe_banner_pattern
    - glow_berries
    - glow_ink_sac
    - glow_item_frame
    - glow_squid_spawn_egg
    - glowstone_dust
    - goat_horn
    - goat_spawn_egg
    - gold_ingot
    - gold_nugget
    - golden_apple
    - golden_axe
    - golden_boots
    - golden_carrot
    - golden_chestplate
    - golden_helmet
    - golden_hoe
    - golden_horse_armor
    - golden_leggings
    - golden_pickaxe
    - golden_shovel
    - golden_sword
    - gray_dye
    - green_dye
    - guardian_spawn_egg
    - gunpowder
    - heart_of_the_sea
    - hoglin_spawn_egg
    - honey_bottle
    - honeycomb
    - hopper_minecart
    - horse_spawn_egg
    - husk_spawn_egg
    - ink_sac
    - iron_axe
    - iron_boots
    - iron_chestplate
    - iron_helmet
    - iron_hoe
    - iron_horse_armor
    - iron_ingot
    - iron_leggings
    - iron_nugget
    - iron_pickaxe
    - iron_shovel
    - iron_sword
    - item_frame
    - jungle_boat
    - jungle_chest_boat
    - knowledge_book
    - lapis_lazuli
    - lava_bucket
    - lead
    - leather
    - leather_boots
    - leather_chestplate
    - leather_helmet
    - leather_horse_armor
    - leather_leggings
    - light_blue_dye
    - light_gray_dye
    - lime_dye
    - lingering_potion
    - llama_spawn_egg
    - lodestone_compass
    - magenta_dye
    - magma_cream
    - magma_cube_spawn_egg
    - mangrove_boat
    - mangrove_chest_boat
    - map
    - melon_seeds
    - melon_slice
    - milk_bucket
    - minecart
    - mojang_banner_pattern
    - mooshroom_spawn_egg
    - mule_spawn_egg
    - mushroom_stew
    - music_disc_11
    - music_disc_13
    - music_disc_5
    - music_disc_blocks
    - music_disc_cat
    - music_disc_chirp
    - music_disc_far
    - music_disc_mall
    - music_disc_mellohi
    - music_disc_otherside
    - music_disc_pigstep
    - music_disc_stal
    - music_disc_strad
    - music_disc_wait
    - music_disc_ward
    - mutton
    - name_tag
    - nautilus_shell
    - nether_brick
    - nether_star
    - nether_wart
    - netherite_axe
    - netherite_boots
    - netherite_chestplate
    - netherite_helmet
    - netherite_hoe
    - netherite_ingot
    - netherite_leggings
    - netherite_pickaxe
    - netherite_scrap
    - netherite_shovel
    - netherite_sword
    - oak_boat
    - oak_chest_boat
    - ocelot_spawn_egg
    - orange_dye
    - painting
    - panda_spawn_egg
    - paper
    - parrot_spawn_egg
    - phantom_membrane
    - phantom_spawn_egg
    - pig_spawn_egg
    - piglin_banner_pattern
    - piglin_brute_spawn_egg
    - piglin_spawn_egg
    - pillager_spawn_egg
    - pink_dye
    - poisonous_potato
    - polar_bear_spawn_egg
    - popped_chorus_fruit
    - porkchop
    - potato
    - potion
    - powder_snow_bucket
    - prismarine_crystals
    - prismarine_shard
    - pufferfish
    - pufferfish_bucket
    - pufferfish_spawn_egg
    - pumpkin_pie
    - pumpkin_seeds
    - purple_dye
    - quartz
    - rabbit
    - rabbit_foot
    - rabbit_hide
    - rabbit_spawn_egg
    - rabbit_stew
    - ravager_spawn_egg
    - raw_copper
    - raw_gold
    - raw_iron
    - recovery_compass
    - red_dye
    - redstone
    - rotten_flesh
    - saddle
    - salmon
    - salmon_bucket
    - salmon_spawn_egg
    - scute
    - shears
    - sheep_spawn_egg
    - shield
    - shulker_shell
    - shulker_spawn_egg
    - sign
    - silverfish_spawn_egg
    - skeleton_horse_spawn_egg
    - skeleton_spawn_egg
    - skull_banner_pattern
    - slime_ball
    - slime_spawn_egg
    - snowball
    - spectral_arrow
    - spider_eye
    - spider_spawn_egg
    - splash_potion
    - spruce_boat
    - spruce_chest_boat
    - spyglass
    - squid_spawn_egg
    - stick
    - stone_axe
    - stone_hoe
    - stone_pickaxe
    - stone_shovel
    - stone_sword
    - stray_spawn_egg
    - strider_spawn_egg
    - string
    - sugar
    - suspicious_stew
    - sweet_berries
    - tadpole_bucket
    - tadpole_spawn_egg
    - tipped_arrow
    - tnt_minecart
    - totem_of_undying
    - trader_llama_spawn_egg
    - trident
    - tropical_fish
    - tropical_fish_bucket
    - tropical_fish_spawn_egg
    - turtle_helmet
    - turtle_spawn_egg
    - vex_spawn_egg
    - villager_spawn_egg
    - vindicator_spawn_egg
    - wandering_trader_spawn_egg
    - warden_spawn_egg
    - warped_fungus_on_a_stick
    - water_bucket
    - wheat
    - wheat_seeds
    - white_dye
    - witch_spawn_egg
    - wither_skeleton_spawn_egg
    - wolf_spawn_egg
    - wooden_axe
    - wooden_hoe
    - wooden_pickaxe
    - wooden_shovel
    - wooden_sword
    - writable_book
    - written_book
    - yellow_dye
    - zoglin_spawn_egg
    - zombie_horse_spawn_egg
    - zombie_spawn_egg
    - zombie_villager_spawn_egg
    - zombified_piglin_spawn_egg