
# 更新插件后, 需要手动修改配置版本号, 才能使用一些具有较大改动的功能
# 更新发布页面会显示版本号和新功能示例
configVersion: 4

dev:
  # true  = 适用于 1.20.4 版本的方法 (需要 ProtocolLib 5.2.0
  # false = 适用于更低版本的旧方法
  listeningMode: true
  # 序列化输入消息, 这有可能影响现有的配置
  serialization: false
  # 对未定义 inherit 的配置使用 FINALLY. 即匹配后停止继续检查
  overallFinally: false

list: # 替换列表

  # 翻译实体名 :: 24.03/m 前 #**苦力怕** 破坏 草方块
  - inspectLength: [240, 1024]
    get: '\{"text":"#([a-z0-9_]+)§f([^"]+)","color":"#31B0E8"\}'
    set: >-
      {"text":"§8#"},
      {"translate":"_$1:TranslatedName_","color":"#31b0e8"},
      {"text":"§f_$2_","color":"#31B0E8"}
    inherit: LINK

  # 翻译物品 :: 24.03/m 前 #苦力怕 破坏 **草方块**
  - inspectLength: [350, 1024]
    get: '\{"text":"([a-z0-9_]+)(?:§f.{0,3})?","color":"#31B0E8"\}'
    set: >-
      {"extra":[
        {"translate":"_$1:TranslatedName_"},
        {"text":" §8_$1_",
          "hoverEvent":{
            "action":"show_text",
            "contents":{"text":"§7点击复制ID\n§8minecraft:_$1_"}
          },
        "clickEvent":{"action":"copy_to_clipboard","value":"_$1_"}
        }
      ],"color":"#31b0e8","text":""}
    inherit: FINALLY

  # [示例] 所有可用配置
    # [可选] 仅对拥有该权限的玩家处理这条消息, 默认所有玩家
  - permission: 'minecraft.command'
    # [必选] 检查消息长度是否在此区间内 (大于50且小于64)
    inspectLength: [50, 64]
    # [必选] 使用正则表达式匹配
    get: '^\{"text":"","extra":\["Missing required argument (\d+)"\]\}$'
    # [必选] 将消息替换为
    # _$1_    = 正则匹配到的变量 1, 也可以是 `_$2_` (第 2 个变量)...
    # _$1:ItemType_   = 将 _$1_ 用于获取物品类型, 提供给 JSON hoverEvent 使用的物品类型 show_entity, show_item(block)
    # _$1:TranslatedName_   = 将 _$1_ 用于名称翻译, 返回与语言路径对应的 KEY, 例如 `entity.minecraft.allay`
    # _$1:Words:组名_   = 将 _$1_ 用于词替换, 需要配置 words.yml
    # 其他示例:
    # set: >- # YAML 语法中使用 `>-` 可以编写换行的文本, 效果如上
    # set: '' # 如果为空, 则取消发送这条消息
    # set: _USE_GET_ # 将 get 匹配到的消息原封不动的搬下来
    set: '{"text":"§bIpacEL §f> §b此指令需要至少§a_$1:Words:中文数字_个参数"}'
    # [可选] 修改消息显示位置
    # ACTION_BAR  = 这条消息将会显示在操作栏
    displayPlace: ACTION_BAR
    # [可选] 修改消息显示对象
    # ALL     = 将消息广播给所有玩家. 仅限于只有自己能收到消息的情况
    # EXCLUDE = 将消息广播给所有玩家, 但不包括自己. 仅限于只有自己能收到消息的情况
    # CONSOLE = 将消息转发到控制台, 自己不会收到
    # COPY_TO_CONSOLE = 将消息复制到控制台
    displayObject: ''
    # [可选] 继承和其他配置. 将多个配置合并为组, 同时处理来提高性能
    # LINK     = 与下一条配置合并为组, 将此配置处理完毕的内容传递给下一条配置, 请确保存在下一条配置
    # LINK_SER = 使 GROUP 传递序列化后的 JSON 文本
    # CLOSE    = 如果匹配, 则立即退出匹配检查循环, 不再处理任何数据
    # FINALLY  = 这条消息处理完毕后退出匹配检查循环
    inherit: FINALLY
